# -*- coding: utf-8 -*-
"""Crypto Data Analysis 2.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AvjUSmUbHkBlnSILW6BDSLG2qkMSZsrK

# Como se comportaram os valores para todas as criptomoedas? Os valores tiveram uma tendência de queda ou de aumento?
"""

# Importação das bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Leitura do conjunto de dados

df1 = pd.read_csv('coin_BinanceCoin.csv')
df2 = pd.read_csv('coin_Cardano.csv')
df3 = pd.read_csv('coin_ChainLink.csv')
df4 = pd.read_csv('coin_CryptocomCoin.csv')
df5 = pd.read_csv('coin_EOS.csv')
df6 = pd.read_csv('coin_Ethereum.csv')
df7 = pd.read_csv('coin_Iota.csv')
df8 = pd.read_csv('coin_NEM.csv')
df9 = pd.read_csv('coin_Tron.csv')
df10 = pd.read_csv('coin_USDCoin.csv')

df = pd.concat([ df1, df2, df3 ,df4, df5, df6, df7, df8, df9, df10])

"""## 1-Como se comportaram os valores para todas as criptomoedas? Os valores tiveram uma tendência de queda ou de aumento?"""

# Vamos plotar um gráfico para visualizar a tendência dos valores ao longo do tempo
plt.figure(figsize=(12, 6))
sns.lineplot(x='Date', y='Close', hue='Name', data=df)
plt.title('Comportamento dos Valores das Criptomoedas')
plt.xlabel('Data')
plt.ylabel('Valor de Fechamento')
plt.xticks(rotation=45)
plt.show()

"""## 2-Quais os valores médios para todas as criptomoedas?"""

# Vamos calcular a média dos valores de fechamento para cada criptomoeda
mean_close_values = df.groupby('Name')['Close'].mean()
print(mean_close_values)

"""## 3-Em quais anos houve maiores quedas e valorizações?"""

# Primeiro, precisamos extrair o ano da coluna 'Date'
df['Year'] = pd.to_datetime(df['Date']).dt.year

# Agora, podemos calcular a variação de preço por ano para cada criptomoeda
df['Variation'] = df.groupby(['Name', 'Year'])['Close'].transform(lambda x: x.pct_change())

# Encontrar o ano com a maior queda e a maior valorização
max_fall_year = df.groupby('Year')['Variation'].min().idxmin()
max_rise_year = df.groupby('Year')['Variation'].max().idxmax()

print(f"Ano com maior queda: {max_fall_year}")
print(f"Ano com maior valorização: {max_rise_year}")

"""## 4-Existe alguma tendência de aumento ou queda dos valores pelo dia da semana?"""

# Primeiro, precisamos extrair o dia da semana da coluna 'Date'
df['DayOfWeek'] = pd.to_datetime(df['Date']).dt.day_name()

# Calcular a média dos valores de fechamento por dia da semana
mean_close_by_day = df.groupby('DayOfWeek')['Close'].mean()
print(mean_close_by_day)

"""## 5-Qual moeda se mostra mais interessante em relação à valorização pela análise da série histórica?"""

# Vamos calcular a variação total para cada criptomoeda
df['TotalVariation'] = df.groupby('Name')['Close'].transform(lambda x: x.iloc[-1] - x.iloc[0])

# Encontrar a criptomoeda com a maior variação total
most_interesting_currency = df.groupby('Name')['TotalVariation'].sum().idxmax()
print(f"A criptomoeda mais interessante em termos de valorização é: {most_interesting_currency}")

"""## 6-Qual moeda se mostra menos interessante em relação à valorização pela análise da série histórica?"""

# Encontrar a criptomoeda com a menor variação total
least_interesting_currency = df.groupby('Name')['TotalVariation'].sum().idxmin()
print(f"A criptomoeda menos interessante em termos de valorização é: {least_interesting_currency}")

"""## 7-Existe correlação entre os valores para todas as criptomoedas?"""

# Vamos calcular a matriz de correlação entre os valores de fechamento
correlation_matrix = df.pivot_table(index='Date', columns='Name', values='Close')
correlation = correlation_matrix.corr()

# Plotar um heatmap da matriz de correlação
plt.figure(figsize=(10, 8))
sns.heatmap(correlation, annot=True, cmap='coolwarm')
plt.title('Correlação entre os Valores de Fechamento das Criptomoedas')
plt.show()

"""# Questões Extras:
### EXTRA 1  

Qual foi a criptomoeda que teve a maior volatilidade ao longo do período analisado?
"""

# Vamos calcular a volatilidade de cada criptomoeda
df['Volatility'] = df.groupby('Name')['Close'].transform(lambda x: x.pct_change().std())

# Encontrar a criptomoeda com a maior volatilidade
most_volatile_currency = df.groupby('Name')['Volatility'].max().idxmax()
print(f"A criptomoeda mais volátil é: {most_volatile_currency}")

"""# EXTRA 2
### Qual foi a criptomoeda com o maior valor máximo de mercado?
"""

# Encontrar a criptomoeda com o maior valor de mercado máximo
max_marketcap_currency = df.groupby('Name')['Marketcap'].max().idxmax()
print(f"A criptomoeda com o maior valor de mercado máximo é: {max_marketcap_currency}")